INSERT INTO public.category (id,name) VALUES (1,'fruit'),(2,'légume'),(3,'fomage'),(4,'viande'),(5,'poisson'),(6,'yaourt'),(7,'boisson');

SELECT pg_catalog.setval('public.category_id_seq', 7, true);

INSERT INTO public.product VALUES (1, 'update !!!', 'Iceland', 27, 7, 3, 'https://www.pourquoidocteur.fr/media/article/thunbs/uploded_istock-687905942-1523707909.jpg', 7, false);
INSERT INTO public.product VALUES (2, 'British Indian Ocean Territory', 'Spain', 22, 10, 3, 'http://www.nospetitsmangeurs.org/wp-content/uploads/2014/06/viande_crue-300x200.jpg', 4, false);
INSERT INTO public.product VALUES (3, 'Tunisia', 'Lesotho', 29, 14, 3, 'https://static.passeportsante.net/i59615-environnement-9-conseils-pour-manger-responsable.jpg', 5, false);
INSERT INTO public.product VALUES (4, 'Moldova', 'Antigua and Barbuda', 29, 7, 3, 'https://www.pourquoidocteur.fr/media/article/thunbs/uploded_istock-687905942-1523707909.jpg', 7, false);
INSERT INTO public.product VALUES (5, 'Fraises', 'Très sucré', 4.25, 5.5, 3, 'https://www.iweiyi.com/1050-tm_large_default/livraison-panier-de-fruits-tropicaux.jpg', 1, false);
INSERT INTO public.product VALUES (6, 'Viet Nam', 'Sao Tome and Principe', 30, 10, 3, 'https://www.laboitedufromager.com/wp-content/uploads/2017/03/Pourquoi-les-fromages-nont-pas-tous-la-m%C3%AAme-texture.jpg', 3, false);
INSERT INTO public.product VALUES (7, 'Peru', 'Czech Republic', 14, 14, 3, 'https://static.passeportsante.net/i59615-environnement-9-conseils-pour-manger-responsable.jpg', 5, false);
INSERT INTO public.product VALUES (8, 'American Samoa', 'Latvia', 21, 19, 3, 'http://www.nospetitsmangeurs.org/wp-content/uploads/2014/06/viande_crue-300x200.jpg', 4, false);
INSERT INTO public.product VALUES (9, 'Egypt', 'Virgin Islands, United States', 12, 5, 3, 'https://www.laboitedufromager.com/wp-content/uploads/2017/03/Pourquoi-les-fromages-nont-pas-tous-la-m%C3%AAme-texture.jpg', 3, false);
INSERT INTO public.product VALUES (10, 'Korea, South', 'Ecuador', 29, 5, 14, 'https://static.passeportsante.net/i59615-environnement-9-conseils-pour-manger-responsable.jpg', 5, false);
INSERT INTO public.product VALUES (11, 'Netherlands', 'Kazakhstan', 25, 16, 7, 'https://www.iweiyi.com/1050-tm_large_default/livraison-panier-de-fruits-tropicaux.jpg', 1, false);
INSERT INTO public.product VALUES (12, 'Chad', 'Oman', 13, 6, 7, 'https://static.cuisineaz.com/400x320/i137376-yaourt-a-la-vanille-de-ma-grand-mere.jpeg', 6, false);
INSERT INTO public.product VALUES (13, 'Hungary', 'Peru', 25, 9, 7, 'https://www.iweiyi.com/1050-tm_large_default/livraison-panier-de-fruits-tropicaux.jpg', 1, false);
INSERT INTO public.product VALUES (14, 'Lithuania', 'Angola', 19, 18, 7, 'https://static.passeportsante.net/i59615-environnement-9-conseils-pour-manger-responsable.jpg', 5, false);
INSERT INTO public.product VALUES (15, 'Brunei', 'Liberia', 15, 20, 14, 'https://static.cuisineaz.com/400x320/i137376-yaourt-a-la-vanille-de-ma-grand-mere.jpeg', 6, false);
INSERT INTO public.product VALUES (16, 'Sao Tome and Principe', 'Cameroon', 30, 14, 8, 'https://www.laboitedufromager.com/wp-content/uploads/2017/03/Pourquoi-les-fromages-nont-pas-tous-la-m%C3%AAme-texture.jpg', 3, false);
INSERT INTO public.product VALUES (17, 'Moldova', 'Italy', 21, 20, 8, 'https://www.iweiyi.com/1050-tm_large_default/livraison-panier-de-fruits-tropicaux.jpg', 1, false);
INSERT INTO public.product VALUES (18, 'Argentina', 'Turkmenistan', 14, 7, 8, 'https://www.pourquoidocteur.fr/media/article/thunbs/uploded_istock-687905942-1523707909.jpg', 7, false);
INSERT INTO public.product VALUES (19, 'Cayman Islands', 'Nepal', 29, 10, 8, 'https://static.passeportsante.net/i59615-environnement-9-conseils-pour-manger-responsable.jpg', 5, false);
INSERT INTO public.product VALUES (20, 'Israel', 'Costa Rica', 14, 19, 1, 'https://www.laboitedufromager.com/wp-content/uploads/2017/03/Pourquoi-les-fromages-nont-pas-tous-la-m%C3%AAme-texture.jpg', 3, false);
INSERT INTO public.product VALUES (21, 'South Georgia and The South Sandwich Islands', 'Singapore', 30, 13, 10, 'https://www.iweiyi.com/1050-tm_large_default/livraison-panier-de-fruits-tropicaux.jpg', 1, false);
INSERT INTO public.product VALUES (22, 'Timor-Leste', 'Togo', 24, 16, 10, 'https://www.oclico.com/4116-large_default/panier-de-fruits-et-legumes-famille-nombreuse.jpg', 2, false);
INSERT INTO public.product VALUES (23, 'Mauritania', 'Thailand', 15, 13, 10, 'https://www.laboitedufromager.com/wp-content/uploads/2017/03/Pourquoi-les-fromages-nont-pas-tous-la-m%C3%AAme-texture.jpg', 3, false);
INSERT INTO public.product VALUES (24, 'Marshall Islands', 'Cambodia', 20, 11, 10, 'https://www.oclico.com/4116-large_default/panier-de-fruits-et-legumes-famille-nombreuse.jpg', 2, false);
INSERT INTO public.product VALUES (25, 'Nicaragua', 'Eritrea', 27, 17, 11, 'https://www.laboitedufromager.com/wp-content/uploads/2017/03/Pourquoi-les-fromages-nont-pas-tous-la-m%C3%AAme-texture.jpg', 3, false);
INSERT INTO public.product VALUES (26, 'Macedonia', 'Sri Lanka', 18, 11, 11, 'https://www.iweiyi.com/1050-tm_large_default/livraison-panier-de-fruits-tropicaux.jpg', 1, false);
INSERT INTO public.product VALUES (27, 'Korea, North', 'Svalbard and Jan Mayen Islands', 29, 5, 11, 'https://www.pourquoidocteur.fr/media/article/thunbs/uploded_istock-687905942-1523707909.jpg', 7, false);
INSERT INTO public.product VALUES (28, 'Pitcairn Islands', 'Estonia', 18, 18, 11, 'http://www.nospetitsmangeurs.org/wp-content/uploads/2014/06/viande_crue-300x200.jpg', 4, false);
INSERT INTO public.product VALUES (29, 'Uganda', 'El Salvador', 30, 17, 11, 'https://static.cuisineaz.com/400x320/i137376-yaourt-a-la-vanille-de-ma-grand-mere.jpeg', 6, false);
INSERT INTO public.product VALUES (30, 'Canada', 'Cyprus', 30, 11, 12, 'https://www.laboitedufromager.com/wp-content/uploads/2017/03/Pourquoi-les-fromages-nont-pas-tous-la-m%C3%AAme-texture.jpg', 3, false);
INSERT INTO public.product VALUES (31, 'Sierra Leone', 'Serbia', 14, 6, 12, 'https://www.laboitedufromager.com/wp-content/uploads/2017/03/Pourquoi-les-fromages-nont-pas-tous-la-m%C3%AAme-texture.jpg', 3, false);
INSERT INTO public.product VALUES (32, 'Turkmenistan', 'Timor-Leste', 16, 17, 12, 'https://www.laboitedufromager.com/wp-content/uploads/2017/03/Pourquoi-les-fromages-nont-pas-tous-la-m%C3%AAme-texture.jpg', 3, false);
INSERT INTO public.product VALUES (33, 'Macedonia', 'Tajikistan', 16, 16, 12, 'https://www.pourquoidocteur.fr/media/article/thunbs/uploded_istock-687905942-1523707909.jpg', 7, false);
INSERT INTO public.product VALUES (34, 'Eritrea', 'Japan', 13, 9, 12, 'https://static.passeportsante.net/i59615-environnement-9-conseils-pour-manger-responsable.jpg', 5, false);
INSERT INTO public.product VALUES (35, 'Tokelau', 'Guatemala', 14, 8, 14, 'https://www.iweiyi.com/1050-tm_large_default/livraison-panier-de-fruits-tropicaux.jpg', 1, false);
INSERT INTO public.product VALUES (36, 'Tuvalu', 'Congo (Brazzaville)', 29, 7, 14, 'http://www.nospetitsmangeurs.org/wp-content/uploads/2014/06/viande_crue-300x200.jpg', 4, false);
INSERT INTO public.product VALUES (37, 'Chile', 'Romania', 26, 10, 14, 'https://static.cuisineaz.com/400x320/i137376-yaourt-a-la-vanille-de-ma-grand-mere.jpeg', 6, false);
INSERT INTO public.product VALUES (38, 'Belgium', 'Saint Kitts and Nevis', 22, 6, 14, 'http://www.nospetitsmangeurs.org/wp-content/uploads/2014/06/viande_crue-300x200.jpg', 4, false);
INSERT INTO public.product VALUES (39, 'Belize', 'Denmark', 21, 8, 14, 'https://www.laboitedufromager.com/wp-content/uploads/2017/03/Pourquoi-les-fromages-nont-pas-tous-la-m%C3%AAme-texture.jpg', 3, false);
INSERT INTO public.product VALUES (40, 'Guadeloupe', 'Nicaragua', 26, 5, 15, 'https://static.cuisineaz.com/400x320/i137376-yaourt-a-la-vanille-de-ma-grand-mere.jpeg', 6, false);
INSERT INTO public.product VALUES (41, 'Kazakhstan', 'Netherlands', 22, 14, 15, 'https://www.pourquoidocteur.fr/media/article/thunbs/uploded_istock-687905942-1523707909.jpg', 7, false);
INSERT INTO public.product VALUES (42, 'Pakistan', 'Thailand', 25, 18, 15, 'https://www.oclico.com/4116-large_default/panier-de-fruits-et-legumes-famille-nombreuse.jpg', 2, false);
INSERT INTO public.product VALUES (43, 'Syria', 'Latvia', 19, 18, 15, 'https://www.pourquoidocteur.fr/media/article/thunbs/uploded_istock-687905942-1523707909.jpg', 7, false);
INSERT INTO public.product VALUES (44, 'Bangladesh', 'Benin', 16, 17, 15, 'https://static.cuisineaz.com/400x320/i137376-yaourt-a-la-vanille-de-ma-grand-mere.jpeg', 6, false);
INSERT INTO public.product VALUES (45, 'Papua New Guinea', 'Tokelau', 15, 15, 16, 'https://www.oclico.com/4116-large_default/panier-de-fruits-et-legumes-famille-nombreuse.jpg', 2, false);
INSERT INTO public.product VALUES (46, 'Thailand', 'South Africa', 21, 6, 16, 'https://www.oclico.com/4116-large_default/panier-de-fruits-et-legumes-famille-nombreuse.jpg', 2, false);
INSERT INTO public.product VALUES (47, 'Greenland', 'Canada', 26, 11, 16, 'https://www.iweiyi.com/1050-tm_large_default/livraison-panier-de-fruits-tropicaux.jpg', 1, false);
INSERT INTO public.product VALUES (48, 'Viet Nam', 'Macedonia', 18, 12, 16, 'https://www.pourquoidocteur.fr/media/article/thunbs/uploded_istock-687905942-1523707909.jpg', 7, false);
INSERT INTO public.product VALUES (49, 'Kuwait', 'Gibraltar', 22, 12, 16, 'https://www.oclico.com/4116-large_default/panier-de-fruits-et-legumes-famille-nombreuse.jpg', 2, false);
INSERT INTO public.product VALUES (50, 'Curaçao', 'Eritrea', 17, 7, 18, 'https://www.oclico.com/4116-large_default/panier-de-fruits-et-legumes-famille-nombreuse.jpg', 2, false);
INSERT INTO public.product VALUES (51, 'Dominican Republic', 'Viet Nam', 29, 14, 18, 'https://www.laboitedufromager.com/wp-content/uploads/2017/03/Pourquoi-les-fromages-nont-pas-tous-la-m%C3%AAme-texture.jpg', 3, false);
INSERT INTO public.product VALUES (52, 'Thailand', 'Madagascar', 17, 11, 18, 'https://static.cuisineaz.com/400x320/i137376-yaourt-a-la-vanille-de-ma-grand-mere.jpeg', 6, false);
INSERT INTO public.product VALUES (53, 'Antigua and Barbuda', 'Christmas Island', 22, 20, 18, 'https://www.iweiyi.com/1050-tm_large_default/livraison-panier-de-fruits-tropicaux.jpg', 1, false);
INSERT INTO public.product VALUES (54, 'Poland', 'Comoros', 22, 9, 18, 'https://www.iweiyi.com/1050-tm_large_default/livraison-panier-de-fruits-tropicaux.jpg', 1, false);
INSERT INTO public.product VALUES (55, 'Tuvalu', 'French Southern Territories', 29, 19, 20, 'https://www.laboitedufromager.com/wp-content/uploads/2017/03/Pourquoi-les-fromages-nont-pas-tous-la-m%C3%AAme-texture.jpg', 3, false);
INSERT INTO public.product VALUES (56, 'Nepal', 'Kyrgyzstan', 25, 12, 20, 'https://www.pourquoidocteur.fr/media/article/thunbs/uploded_istock-687905942-1523707909.jpg', 7, false);
INSERT INTO public.product VALUES (57, 'Kyrgyzstan', 'Kenya', 24, 6, 20, 'https://www.laboitedufromager.com/wp-content/uploads/2017/03/Pourquoi-les-fromages-nont-pas-tous-la-m%C3%AAme-texture.jpg', 3, false);
INSERT INTO public.product VALUES (58, 'Guadeloupe', 'Sudan', 14, 6, 20, 'https://www.oclico.com/4116-large_default/panier-de-fruits-et-legumes-famille-nombreuse.jpg', 2, false);
INSERT INTO public.product VALUES (59, 'Indonesia', 'Ethiopia', 17, 17, 20, 'https://www.pourquoidocteur.fr/media/article/thunbs/uploded_istock-687905942-1523707909.jpg', 7, false);
INSERT INTO public.product VALUES (60, 'Malawi', 'Timor-Leste', 29, 5, 23, 'https://www.laboitedufromager.com/wp-content/uploads/2017/03/Pourquoi-les-fromages-nont-pas-tous-la-m%C3%AAme-texture.jpg', 3, false);
INSERT INTO public.product VALUES (61, 'Italy', 'Cook Islands', 21, 16, 23, 'https://www.pourquoidocteur.fr/media/article/thunbs/uploded_istock-687905942-1523707909.jpg', 7, false);
INSERT INTO public.product VALUES (62, 'Hong Kong', 'Niue', 29, 13, 23, 'https://www.laboitedufromager.com/wp-content/uploads/2017/03/Pourquoi-les-fromages-nont-pas-tous-la-m%C3%AAme-texture.jpg', 3, false);
INSERT INTO public.product VALUES (63, 'Ukraine', 'Libya', 18, 7, 23, 'https://static.cuisineaz.com/400x320/i137376-yaourt-a-la-vanille-de-ma-grand-mere.jpeg', 6, false);
INSERT INTO public.product VALUES (64, 'Madagascar', 'Libya', 12, 13, 23, 'http://www.nospetitsmangeurs.org/wp-content/uploads/2014/06/viande_crue-300x200.jpg', 4, false);
INSERT INTO public.product VALUES (65, 'Sudan', 'Paraguay', 15, 5, 24, 'https://www.pourquoidocteur.fr/media/article/thunbs/uploded_istock-687905942-1523707909.jpg', 7, false);
INSERT INTO public.product VALUES (66, 'Hong Kong', 'Norfolk Island', 27, 11, 24, 'https://www.pourquoidocteur.fr/media/article/thunbs/uploded_istock-687905942-1523707909.jpg', 7, false);
INSERT INTO public.product VALUES (67, 'Reunion', 'Svalbard and Jan Mayen Islands', 14, 8, 24, 'https://www.oclico.com/4116-large_default/panier-de-fruits-et-legumes-famille-nombreuse.jpg', 2, false);
INSERT INTO public.product VALUES (68, 'Georgia', 'Uganda', 14, 11, 24, 'https://www.iweiyi.com/1050-tm_large_default/livraison-panier-de-fruits-tropicaux.jpg', 1, false);
INSERT INTO public.product VALUES (69, 'Somalia', 'Brazil', 14, 20, 24, 'http://www.nospetitsmangeurs.org/wp-content/uploads/2014/06/viande_crue-300x200.jpg', 4, false);
INSERT INTO public.product VALUES (70, 'Tanzania', 'Indonesia', 12, 12, 25, 'http://www.nospetitsmangeurs.org/wp-content/uploads/2014/06/viande_crue-300x200.jpg', 4, false);
INSERT INTO public.product VALUES (71, 'Bahrain', 'Laos', 12, 11, 25, 'https://www.iweiyi.com/1050-tm_large_default/livraison-panier-de-fruits-tropicaux.jpg', 1, false);
INSERT INTO public.product VALUES (72, 'Greece', 'Yemen', 29, 8, 25, 'https://static.passeportsante.net/i59615-environnement-9-conseils-pour-manger-responsable.jpg', 5, false);
INSERT INTO public.product VALUES (73, 'Lebanon', 'Marshall Islands', 13, 11, 25, 'http://www.nospetitsmangeurs.org/wp-content/uploads/2014/06/viande_crue-300x200.jpg', 4, false);
INSERT INTO public.product VALUES (74, 'Austria', 'Bahamas', 20, 13, 25, 'http://www.nospetitsmangeurs.org/wp-content/uploads/2014/06/viande_crue-300x200.jpg', 4, false);
INSERT INTO public.product VALUES (75, 'Honduras', 'Saint Lucia', 20, 14, 28, 'https://www.iweiyi.com/1050-tm_large_default/livraison-panier-de-fruits-tropicaux.jpg', 1, false);
INSERT INTO public.product VALUES (76, 'Palestine, State of', 'Mali', 15, 12, 28, 'https://www.iweiyi.com/1050-tm_large_default/livraison-panier-de-fruits-tropicaux.jpg', 1, false);
INSERT INTO public.product VALUES (77, 'Jersey', 'Nauru', 19, 19, 28, 'https://www.oclico.com/4116-large_default/panier-de-fruits-et-legumes-famille-nombreuse.jpg', 2, false);
INSERT INTO public.product VALUES (78, 'Svalbard and Jan Mayen Islands', 'Ghana', 13, 10, 28, 'https://static.cuisineaz.com/400x320/i137376-yaourt-a-la-vanille-de-ma-grand-mere.jpeg', 6, false);
INSERT INTO public.product VALUES (79, 'Trinidad and Tobago', 'Tanzania', 12, 11, 28, 'https://www.iweiyi.com/1050-tm_large_default/livraison-panier-de-fruits-tropicaux.jpg', 1, false);
INSERT INTO public.product VALUES (80, 'Virgin Islands, British', 'Ghana', 21, 18, 30, 'https://www.laboitedufromager.com/wp-content/uploads/2017/03/Pourquoi-les-fromages-nont-pas-tous-la-m%C3%AAme-texture.jpg', 3, false);
INSERT INTO public.product VALUES (81, 'Honduras', 'Faroe Islands', 21, 11, 30, 'https://static.cuisineaz.com/400x320/i137376-yaourt-a-la-vanille-de-ma-grand-mere.jpeg', 6, false);
INSERT INTO public.product VALUES (82, 'Mongolia', 'Falkland Islands', 17, 11, 30, 'http://www.nospetitsmangeurs.org/wp-content/uploads/2014/06/viande_crue-300x200.jpg', 4, false);
INSERT INTO public.product VALUES (83, 'Chad', 'Namibia', 25, 14, 30, 'https://www.pourquoidocteur.fr/media/article/thunbs/uploded_istock-687905942-1523707909.jpg', 7, false);
INSERT INTO public.product VALUES (84, 'Virgin Islands, United States', 'Christmas Island', 24, 19, 30, 'https://www.oclico.com/4116-large_default/panier-de-fruits-et-legumes-famille-nombreuse.jpg', 2, false);
INSERT INTO public.product VALUES (85, 'Heard Island and Mcdonald Islands', 'Cayman Islands', 13, 9, 35, 'https://static.cuisineaz.com/400x320/i137376-yaourt-a-la-vanille-de-ma-grand-mere.jpeg', 6, false);
INSERT INTO public.product VALUES (86, 'Rwanda', 'Singapore', 23, 20, 35, 'https://static.cuisineaz.com/400x320/i137376-yaourt-a-la-vanille-de-ma-grand-mere.jpeg', 6, false);
INSERT INTO public.product VALUES (87, 'Andorra', 'Czech Republic', 28, 18, 35, 'https://www.pourquoidocteur.fr/media/article/thunbs/uploded_istock-687905942-1523707909.jpg', 7, false);
INSERT INTO public.product VALUES (88, 'Guernsey', 'Finland', 15, 17, 35, 'https://www.pourquoidocteur.fr/media/article/thunbs/uploded_istock-687905942-1523707909.jpg', 7, false);
INSERT INTO public.product VALUES (89, 'Swaziland', 'Cuba', 25, 10, 35, 'http://www.nospetitsmangeurs.org/wp-content/uploads/2014/06/viande_crue-300x200.jpg', 4, false);
INSERT INTO public.product VALUES (90, 'United States Minor Outlying Islands', 'Eritrea', 21, 10, 38, 'http://www.nospetitsmangeurs.org/wp-content/uploads/2014/06/viande_crue-300x200.jpg', 4, false);
INSERT INTO public.product VALUES (91, 'United States Minor Outlying Islands', 'Cyprus', 19, 10, 38, 'https://www.oclico.com/4116-large_default/panier-de-fruits-et-legumes-famille-nombreuse.jpg', 2, false);
INSERT INTO public.product VALUES (92, 'Cayman Islands', 'Saint Martin', 20, 13, 38, 'https://www.laboitedufromager.com/wp-content/uploads/2017/03/Pourquoi-les-fromages-nont-pas-tous-la-m%C3%AAme-texture.jpg', 3, false);
INSERT INTO public.product VALUES (93, 'Bahamas', 'Namibia', 27, 11, 38, 'https://www.pourquoidocteur.fr/media/article/thunbs/uploded_istock-687905942-1523707909.jpg', 7, false);
INSERT INTO public.product VALUES (94, 'Tonga', 'French Guiana', 13, 9, 38, 'https://static.passeportsante.net/i59615-environnement-9-conseils-pour-manger-responsable.jpg', 5, false);
INSERT INTO public.product VALUES (95, 'Belize', 'Macedonia', 18, 14, 39, 'http://www.nospetitsmangeurs.org/wp-content/uploads/2014/06/viande_crue-300x200.jpg', 4, false);
INSERT INTO public.product VALUES (96, 'Belize', 'Saint Vincent and The Grenadines', 15, 7, 39, 'http://www.nospetitsmangeurs.org/wp-content/uploads/2014/06/viande_crue-300x200.jpg', 4, false);
INSERT INTO public.product VALUES (97, 'Suriname', 'Bermuda', 27, 9, 39, 'http://www.nospetitsmangeurs.org/wp-content/uploads/2014/06/viande_crue-300x200.jpg', 4, false);
INSERT INTO public.product VALUES (98, 'Togo', 'Åland Islands', 18, 10, 39, 'https://static.cuisineaz.com/400x320/i137376-yaourt-a-la-vanille-de-ma-grand-mere.jpeg', 6, false);
INSERT INTO public.product VALUES (99, 'Bangladesh', 'Ireland', 22, 18, 39, 'https://static.cuisineaz.com/400x320/i137376-yaourt-a-la-vanille-de-ma-grand-mere.jpeg', 6, false);
INSERT INTO public.product VALUES (100, 'Turkmenistan', 'Virgin Islands, United States', 28, 16, 40, 'https://static.cuisineaz.com/400x320/i137376-yaourt-a-la-vanille-de-ma-grand-mere.jpeg', 6, false);
INSERT INTO public.product VALUES (101, 'Melon du Zimbawé', 'Chez Mamadou les prix sont doux, 10 Fr !', 10, 0, 40, 'https://www.iweiyi.com/1050-tm_large_default/livraison-panier-de-fruits-tropicaux.jpg', 1, false);

SELECT pg_catalog.setval('public.product_id_seq', 101, true);